---
# tasks file for ios_checks


- name: collect output from ios device
  ios_command:
    commands:
      - show version
      - show interfaces
      - show running-config
  register: output

- name: set hostname fact
  set_fact:
    hostname: "{{ output.stdout[2] | regex_search('\nhostname (.+)', '\\1') | first }}"

- name: set model number
  set_fact:
    model_number: "{{ output.stdout[0] | regex_search('[Cc]isco (.+) \\(revision', '\\1') | first | regex_search('(\\d+)') }}"

- name: set interfaces fact
  set_fact:
    interfaces: "{{ output.stdout[1] | regex_findall('\n([L|G|A|B|C|D||M|N|P|T|V]\\S+)') }}"

- name: set version fact
  set_fact:
    version: "{{ output.stdout[0] | regex_search('Version (\\S+)', '\\1') | first }}"

- name: print hostname
  debug:
    msg:
      - "Hostname: {{ hostname }}"
      - " Model Number: {{ model_number }}"
      - " Version: {{ version }}"

- name: print interfaces
  debug:
    var: interfaces

# - name: Retrieve router facts
#   ios_facts:
#   register: facts_output
#
# - name: set facts:
#   set_fact:
#
#
# - name: Show router status
#   debug:
#     msg:
#       #- "Hostname: {{ facts_output.ansible_net_hostname }}"
#       - "IOS Version: {{ facts_output.ansible_net_version }}"
# - name: Show router status
#   ios_command:
#     commands:
#       - show ip interface brief
#       - show ip route summary
#       - show ip bgp summary
#   register: all_interfaces
#
# - name: print router status
#   debug:
#     var: all_interfaces

# - name: Show Interface
#   debug:
#     msg: "{{ output.stdout[1] | regex_findall('\n([E|L|P|V]\\S+)') }}"
#     #msg: "{{ output.stdout[2] | regex_findall('\\s+hostname \\s+(\\S+)') | first }}"
#     #msg: "{{ output.stdout[2] | regex_findall('hostname') | first }}"
#     #msg: "{{ output.stdout[2] }}"
#
# - name: set hostname fact
#   set_fact:
#     hostname: "{{ output.stdout[0] | regex_findall('\\s+Device name:\\s+(\\S+)') | first }}"
#
# - name: set interfaces fact
#   set_fact:
#     interfaces: "{{ output.stdout[1] | regex_findall('\n([E|L|P|V]\\S+)') }}"
#
# - name: set version fact
#   set_fact:
#     version: "{{ output.stdout[0] | regex_findall('(system|NXOS):\\s+version\\s+(\\S+)') | first }}"
#
# - name: set config fact
#   set_fact:
#     config: "{{ output.stdout[2] }}"
#
# - name: set config_lines fact
#   set_fact:
#     config_lines: "{{ config.split('\n') }}"
#
# - name: Print out
#   debug:
    # msg:
    #   - "hostname: {{ec2_name_prefix}}"
    #   - "version: {{ ec2_vpc_id2 }}"
