---
# tasks file for ios_checks


- name: collect output from ios device
  ios_facts:


- name: print router status
  debug:
    msg:
      - "Hostname: {{ ansible_net_hostname }}"
      - "Model Number: {{ ansible_net_model }}"
      - "Software Version: {{ ansible_net_version }}"
      - "Serial Number: {{ ansible_net_serialnum}}"
      #- "Interface: {{ ansible_net_interfaces }}"

- name: print interfaces
  debug:
      msg: "Interface: {{ item.key }} IP Address: {{ item.value.ipv4 }}"
  with_dict: "{{ ansible_net_interfaces }}"
