---
# tasks file for ios_checks


- name: collect output from ios device
  ios_command:
    commands:
      - show version
      - show interface
      - show running-config all
      - show ip interface brief
  register: output

- name: Show output
  debug:
    #msg: "{{ output.stdout[2] | regex_findall('\\s+hostname \\s+(\\S+)') | first }}"
    msg: "{{ output.stdout[2] | regex_findall('hostname \\s+(\\S+)') | first }}"
    #msg: "{{ output.stdout[2] }}"
