---
- name: Remove index.html from webserver
  hosts: webserver
  become: yes

  tasks:

  tasks:
  - name: remove index.html
    file:
      name: /var/www/html/index.html
      state: absent
    notify:
      - restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
