---
- hosts: cisco
  connection: local
  gather_facts: no

  # roles:
  #   - { role: ios_checks, my_array: "{{ groups.cisco }}" }

  tasks:

    - name: debug router names
      debug:
        msg: "{{item}}"
      with_items: "{{ groups['cisco'] }}"

    # - name: Perform IOS checks
    #   include_role:
    #     name: ios_checks
    #   vars:
    #     router: "{{ item }}"
    #   with_items: "{{ groups['cisco'] }}"
