---
- name: Restore router configurations
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
  - name: COPY RUNNING CONFIG TO ROUTER
    net_put:
      src: ./backup/{{inventory_hostname}}.config
      dest: flash:{{inventory_hostname}}.config

  - name: CONFIG REPLACE
    ios_command:
      commands:
        - config replace flash:{{inventory_hostname}}.config force
