---
- hosts: cisco
  connection: local
  gather_facts: no

  # roles:
  #   - { role: ios_checks, my_array: "{{ groups.cisco }}" }

  tasks:

  - name: collect output from ios device
    ios_command:
      host: "{{ item }}"
      commands:
        - show version
        - show interface
        - show running-config all
        - show ip interface brief
    with_items: "{{ groups['cisco'] }}"
