---
- hosts: cisco
  connection: local
  gather_facts: no

  # roles:
  #   - { role: ios_checks, my_array: "{{ groups.cisco }}" }

  tasks:



  - name: Call ios_checks role
    include_role:
      name: ios_checks
