---
- hosts: cisco
  connection: local
  gather_facts: no

  # roles:
  #   - { role: ios_checks, my_array: "{{ groups.cisco }}" }

  tasks:

    - name: Perform IOS checks
      include_role:
        name: ios_checks
      with_items: "{{ groups['cisco'] }}"
