---
- hosts: cisco
  connection: local
  gather_facts: no

  # roles:
  #   - { role: ios_checks, my_array: "{{ groups.cisco }}" }

  tasks:

  - name: collect output from ios device
    ios_command:
      commands:
        - show version
        - show interface
        - show running-config all
        - show ip interface brief
    register: output

  - name: Show output
    debug:
      msg: "{{ output.stdout[0] | regex_findall('\\s+Device name:\\s+(\\S+)') | first }}"
