---
- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: no
  gather_facts: no


  tasks:
    - name: make sure we are running correct Ansible Version
      assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 6

- name: Deploy Webserver environment in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - manage_ec2_instances
