---
- name: Add IPv6 addresses to loopback interfaces
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Include vars of iterate_hosts.yaml
    include_vars:
      file: iterate_hosts.yml
      # name: ipv6_addresses
    run_once: true

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - ipv6 address "{{ item.value.loopback20 }}" eui-64
        - no shutdown
      parent: interface20
    with_dict: "{{ ipv6_addresses }}"

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - ipv6 address "{{ item.value.loopback30 }}" eui-64
        - no shutdown
      parent: interface30
    with_dict: "{{ ipv6_addresses }}"

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - ipv6 address "{{ item.value.loopback40 }}" eui-64
        - no shutdown
      parent: interface40
    with_dict: "{{ ipv6_addresses }}"

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - ipv6 address "{{ item.value.loopback50 }}" eui-64
        - no shutdown
      parent: interface50
    with_dict: "{{ ipv6_addresses }}"
