---
- name: Add IPv6 addresses to loopback interfaces
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:

  # - name: Include vars of iterate_hosts.yaml
  #   include_vars:
  #     file: iterate_hosts.yml
  #     # name: ipv6_addresses
  #   run_once: true

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - "ipv6 address 2001:DB8:0:2:: eui-64"
        - no shutdown
      parents: interface20

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - "ipv6 address 2001:DB8:0:3:: eui-64"
        - no shutdown
      parents: interface30

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - "ipv6 address 2001:DB8:0:4:: eui-64"
        - no shutdown
      parents: interface40

  - name: Add IPv6 Addresses to all loopback interfaces on all hosts
    ios_config:
      lines:
        - "ipv6 address 2001:DB8:0:5:: eui-64"
        - no shutdown
      parents: interface50
