---
- name: Parse Interfaces on IOS routers
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
  - name: import network-engine role
    import_role:
      name: ../roles/ansible-network.network-engine

  - name: run command on ios and return result
    cli_command:
      command: show interfaces
    register: interfaces

  - name: parse interfaces using command_parser engine
    command_parser:
      file: "parser_templates/show_interfaces.yml"
      content: "{{ interfaces.stdout }}"
      # content: "{{ lookup(‘file’, ‘show_interfaces’ }}"
