---
- hosts: localhost
  connection: local
  gather_facts: False
  become: yes

  tasks:

  - name: Find config file containing {{ inventory_hostname }}
    find:
      paths: "{{ playbook_dir}}/backup"
      contains: "{{ inventory_hostname }}"
    register: find_output

  - name: List Find Output
    debug:
      msg: {{ item }}
    with_items: {{ find_output.files }}

  # - name: Ensure Network Element Directory Exists
  #   file:
  #     path: ""
  #     state: directory
  #   delegate_to: localhost
  #   become: yes
  #
  # - name: Rename Backup File
  #   copy:
  #     src: "{{config_output.backup_path}}"
  #     dest: "/home/mford/git_workspace/ios-config-archives/{{inventory_hostname}}/{{inventory_hostname}}_{{ansible_date_time.epoch}}_{{ansible_date_time.date}}.config"
  #   delegate_to: localhost
  #   become: yes
  #
  # - name: Remove Non Config Lines
  #   lineinfile:
  #     path: "/home/mford/git_workspace/ios-config-archives/{{inventory_hostname}}/{{inventory_hostname}}_{{ansible_date_time.epoch}}_{{ansible_date_time.date}}.config"
  #     line: "Building configuration..."
  #     state: absent
  #   delegate_to: localhost
  #   become: yes
  #
  # - name: Remove Non Config Lines - Regexp
  #   lineinfile:
  #     path: "/home/mford/git_workspace/ios-config-archives/{{inventory_hostname}}/{{inventory_hostname}}_{{ansible_date_time.epoch}}_{{ansible_date_time.date}}.config"
  #     regexp: 'Current configuration.*'
  #     state: absent
  #   delegate_to: localhost
  #   become: yes
  #
  # - name: Remove Local Backup Directory
  #   file:
  #     path: ./backup/
  #     state: absent
  #   delegate_to: localhost
  #   become: yes
  #
  # - name: Push Configuration Backup to GitHub Repository
  #   shell: "{{ item }}"
  #   args:
  #     chdir: ../ios-config-archives/
  #   with_items:
  #     - "git add ."
  #     - "git commit -m 'Config Backup {{inventory_hostname}}_{{ansible_date_time.epoch}}_{{ansible_date_time.date}}.config'"
  #     - "git push"
  #   delegate_to: localhost
  #   become: yes
  #
  # - name: Compare running config to master Config
  #   shell: "diff {{inventory_hostname}}_{{ansible_date_time.epoch}}_{{ansible_date_time.date}}.config {{inventory_hostname}}_master.config"
  #   args:
  #     chdir: "../ios-config-archives/{{inventory_hostname}}/"
  #   register: result
  #   delegate_to: localhost
  #   become: yes
  #   failed_when: result.rc > 1
  #   changed_when: result.rc == 1
  #
  # - name: report diff output
  #   debug:
  #     var: result.stdout
