---
- hosts: cisco
  connection: network_cli
  gather_facts: False

  tasks:

  - name: check the running-config against master config
    ios_config:
      diff_against: intended
      intended_config: "{{ lookup('file', 'rtr1.config') }}"
