---
- name: ADD BGP TO ROUTER1
  hosts: rtr1
  gather_facts: no
  connection: network_cli

  tasks:
      
    - name: ADD BGP 65412 TO  BIGBADGTRROUTER
      ios_config:
        commands:
          - router bgp 65412
          - bgp router-id 10.3.1.4
          - bgp log-neighbor-changes
          - neighbor 10.3.1.5 remote-as 65412

- name: CONFIGURE BGP ON BIGBADSIFMUROUTER
  hosts: rtr2
  gather_facts: no
  connection: network_cli

  tasks:

    - name: ADD BGP CONFIG TO BIGBADSIFMUROUTER
      ios_config:
        src: bgp2.cfg        

- name: SH BGP SUMMARY
  hosts: cisco
  gather_facts: no
  connection: network_cli
  
  roles:
   - ansible-network.network-engine

  tasks:
  
    - name: CAPTURE SHOW IP BGP SUM
      ios_command:
        commands:
          - show ip bgp summary
      register: output

#    - name: PARSE THE RAW OUTPUT
#      command_parser:
#        file: "parsers/show_interfaces.yaml"
#        content: "{{ output.stdout[0] }}"

#    - name: DISPLAY THE PARSED DATA
#      debug:
#        var: interface_facts