- name: grab facts for webserver node (IOSWORKSHOP MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      # "tag:Workshop_host1": "{{ec2_name_prefix}}-webserver"
      "tag:Name": "{{ec2_name_prefix}}-webserver"
  register: host1_node_facts

- name: add webserver to groups (IOSWORKSHOP MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    # short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ ec2_login_names[host1_node] }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - lab_hosts
      - webserver
      - managed_nodes
  with_items: "{{ host1_node_facts.instances }}"

- name: grab facts for rtr1 node (IOSWORKSHOP MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      # "tag:Workshop_rtr1": "{{ec2_name_prefix}}-rtr1"
      "tag:Name": "{{ec2_name_prefix}}-rtr1"
  register: rtr1_node_facts


- name: grab facts for rtr2 node (IOSWORKSHOP MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      # "tag:Workshop_rtr2": "{{ec2_name_prefix}}-rtr2"
      "tag:Name": "{{ec2_name_prefix}}-rtr2"
  register: rtr2_node_facts

  ##### Router 3 ####
- name: grab facts for rtr3 node (NETWORKING MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      # "tag:Workshop_rtr3": "{{ec2_name_prefix}}-rtr3"
      "tag:Name": "{{ec2_name_prefix}}-rtr4"
  register: rtr3_node_facts

##### Router 4 #####
- name: grab facts for rtr4 node (NETWORKING MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      # "tag:Workshop_rtr4": "{{ec2_name_prefix}}-rtr4"
      "tag:Name": "{{ec2_name_prefix}}-rtr4"
  register: rtr4_node_facts


- name: ADD CORE ROUTERS TO INVENTORY
  add_host:
    name: "{{ item.tags.Name }}"
    # short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    # username: "{{ item.tags.Student }}"
    ansible_user: ec2-user
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    ansible_network_os: ios
    groups:
      - routers
      - core
  with_items:
    - "{{ rtr1_node_facts.instances }}"
    - "{{ rtr2_node_facts.instances }}"

- name: ADD ACCESS ROUTERS TO INVENTORY
  add_host:
    name: "{{ item.tags.Name }}"
    # short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    # username: "{{ item.tags.Student }}"
    ansible_user: ec2-user
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    ansible_network_os: ios
    groups:
      - routers
      - access
  with_items:
    - "{{ rtr3_node_facts.instances }}"
    - "{{ rtr4_node_facts.instances }}"

- name: ADD DMVPN HUB ROUTER TO SEPARATE GROUP
  add_host:
    name: "{{ item.tags.Name }}"
    # short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    # username: "{{ item.tags.Student }}"
    ansible_user: ec2-user
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    ansible_network_os: ios
    rtr1_node_facts: "{{rtr1_node_facts}}"
    groups:
      - dmvpn
  with_items:
    - "{{ rtr1_node_facts.instances }}"

- name: Generate Inventory
  template:
    src: ios_instances.txt.j2
    dest: "{{ playbook_dir }}/inventory/hosts"
  delegate_to: localhost
