- include_tasks: teardown.yml
  when: teardown

- name: provision workshop in AWS public cloud
  block:
    - name: provision aws resources and instances
      include_tasks: provision.yml

    - name: create inventory
      include_tasks: create_inventory.yml
  when: not teardown
